### ISSUE TITLE
Facebook user uids for new users are out of integer range for database column fb_uid

### ISSUE THREAD

**Issue by crimefighter** [upstream-archive/simple_facebook_connect#2]
I've just got this problem with PotrgreSQL so i suggest changing simple_facebook_connect migration to use bigger integer or string.
Facebook Connect Developer states that user id is 64 bit integer and recommends to use big int for storing it in databases. (http://wiki.developers.facebook.com/index.php/User_ID)

**Comment by genevievebelle** [comment]
This Repository is reviewed to be supported anymore as part of end of year closing of issues
